# Generated by Django 2.2.4 on 2020-08-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='photo1',
            field=models.ImageField(default='images/products/default.jpg', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.ImageField(default='images/products/default.jpg', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo3',
            field=models.ImageField(default='images/products/default.jpg', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo4',
            field=models.ImageField(default='images/products/default.jpg', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo5',
            field=models.ImageField(default='images/products/default.jpg', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_photo',
            field=models.ForeignKey(default='images/products/default.jpg', on_delete=django.db.models.deletion.CASCADE, related_name='photos_included', to='main.PhotoType'),
            preserve_default=False,
        ),
    ]
