# Generated by Django 2.2.4 on 2020-08-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200826_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_of_photo',
        ),
        migrations.AddField(
            model_name='phototype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phototype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(default='images/products/default.jpg', upload_to='images/products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.Product')),
                ('type_of_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_included', to='main.PhotoType')),
            ],
        ),
    ]
