# Generated by Django 2.2.4 on 2020-08-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200826_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.ImageField(upload_to='images/products'),
        ),
    ]
