# Generated by Django 2.2.4 on 2020-08-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='some_new_field',
            field=models.CharField(default='', max_length=50),
        ),
    ]
